spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://dev-229121.okta.com/oauth2/default/v1/keys
  jpa:
    database-platform: org.hibernate.dialect.SQLiteDialect
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:sqlite:bike.db
    username:
    password:
    driver-class-name: org.sqlite.JDBC

logging:
  level:
    root: info
    org.springframework.web: info
server:
  port: 8097