spring:
  jpa:
    database-platform: org.hibernate.dialect.SQLiteDialect
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:sqlite:bike.db
    username:
    password:
    driver-class-name: org.sqlite.JDBC
  security:
    oauth2:
      client:
        registration:
          okta:
            issuer: https://dev-229121.okta.com/oauth2/default
            scope: openid
            client-id: 0oao3ne1d7yZA2agd356
            client-secret: _GuP_74Zgwx1VP4yEIbYqoZShWHpgIJFv0RV20NG
  security:
    okta:
      oauth2:
        issuer: https://dev-229121.okta.com/oauth2/default
          scope: openid
          client-id: 0oao3ne1d7yZA2agd356
          client-secret: _GuP_74Zgwx1VP4yEIbYqoZShWHpgIJFv0RV20NG
logging:
  level:
    root: info
    org.springframework.web: info
server:
  port: 8097